//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelQuoteApplication14.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Client_Info
    {
        public int Id { get; set; }


        public string FullName { get; set; }

        public string Address1 { get; set; }
        
        public string Address2 { get; set; }

        
        public string City { get; set; }

        
        public string State { get; set; }

        
        public float ZipCode { get; set; }

        public string ErrorMessage { get; set; }
    }
}
