//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelQuoteApplication14.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Quote
    {
        public double Quote_id { get; set; }
        public int Id { get; set; }

        
        public double Gallons_requested { get; set; }

       
        public System.DateTime Delivery_date { get; set; }
        public double Total_amount { get; set; }
        public string Address { get; set; }
        public double price_per_gallon { get; set; }
    }
}
